name: Build Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    environment: Deployment
    outputs:
      manifest: ${{ steps.changes.outputs.manifest }}
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          manifest:
            - 'manifest.json'
  build:
    needs: check-changes
    if: needs.check-changes.outputs.manifest == 'true'
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
    - uses: actions/checkout@v3

    - name: Zipping resources
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r addon.zip icons popup manifest.json background.js
    - name: Archive build result
      uses: actions/upload-artifact@v3
      with:
        name: addon-package
        path: addon.zip
    - name: Publish extension
      uses: trmcnvn/firefox-addon@v1
      with:
        uuid: '{358bea92-053f-4e1d-8397-02ba42e20c41}'
        xpi: addon.zip
        manifest: manifest.json
        api-key: ${{ secrets.FIREFOX_API_KEY }}
        api-secret: ${{ secrets.FIREFOX_API_SECRET }}
